-- MySQL Script generated by MySQL Workbench
-- Wed Aug 19 23:56:38 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`users` ;

CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `idusers` INT NOT NULL,
  `usermail` VARCHAR(45) NULL,
  `username` VARCHAR(45) NULL,
  `userlastname` VARCHAR(45) NULL,
  `userbirthday` VARCHAR(45) NULL,
  `usersex` VARCHAR(45) NULL,
  `usercountry` VARCHAR(45) NULL,
  PRIMARY KEY (`idusers`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`bookreview`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`bookreview` ;

CREATE TABLE IF NOT EXISTS `mydb`.`bookreview` (
  `idbookreview` INT NOT NULL,
  `bookreviewtitle` VARCHAR(45) NULL,
  `bookreviewdescriptions` VARCHAR(500) NULL,
  `bookreviewtag` VARCHAR(45) NULL,
  `users_idusers` INT NOT NULL,
  PRIMARY KEY (`idbookreview`),
  INDEX `fk_bookreview_users_idx` (`users_idusers` ASC) VISIBLE,
  CONSTRAINT `fk_bookreview_users`
    FOREIGN KEY (`users_idusers`)
    REFERENCES `mydb`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`aboutbook`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`aboutbook` ;

CREATE TABLE IF NOT EXISTS `mydb`.`aboutbook` (
  `idaboutbook` INT NOT NULL,
  `aboutbooktitle` VARCHAR(45) NULL,
  `aboutbookgenere` VARCHAR(45) NULL,
  `aboutbookauthor` VARCHAR(45) NULL,
  `aboutbookyearpublications` VARCHAR(45) NULL,
  `bookreview_idbookreview` INT NOT NULL,
  PRIMARY KEY (`idaboutbook`),
  INDEX `fk_aboutbook_bookreview1_idx` (`bookreview_idbookreview` ASC) VISIBLE,
  CONSTRAINT `fk_aboutbook_bookreview1`
    FOREIGN KEY (`bookreview_idbookreview`)
    REFERENCES `mydb`.`bookreview` (`idbookreview`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
